info: Connected to the database. {"timestamp":"2022-11-11T04:24:43.124Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T04:27:52.307Z"}
info: Connected to the database. {"timestamp":"2022-11-11T04:27:55.324Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-11-11T04:29:24.031Z"}
info: Connected to the database. {"timestamp":"2022-11-11T04:29:27.011Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T04:38:13.116Z"}
info: Connected to the database. {"timestamp":"2022-11-11T04:38:13.179Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T04:43:54.188Z"}
info: Connected to the database. {"timestamp":"2022-11-11T04:43:54.290Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T05:09:06.778Z"}
info: Connected to the database. {"timestamp":"2022-11-11T05:09:06.825Z"}
error: 
    status - 500 
    message - ValidationError: "password" length must be at least 8 characters long 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-11T05:11:04.687Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T05:12:44.896Z"}
info: Connected to the database. {"timestamp":"2022-11-11T05:12:44.960Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T05:14:14.332Z"}
info: Connected to the database. {"timestamp":"2022-11-11T05:14:14.400Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T05:17:28.998Z"}
info: Connected to the database. {"timestamp":"2022-11-11T05:17:29.063Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: fundoodb.users index: email_1 dup key: { email: "sunilah007@gmail.com" } 
      url - /api/v1/users/register 
      method - POST 
      IP - ::1
     {"timestamp":"2022-11-11T05:17:59.198Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.writeHead (node:_http_server:314:11)
    at ServerResponse.writeHead (E:\fundo-project\fundoo\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:305:8)
    at write_ (node:_http_outgoing:867:9)
    at ServerResponse.end (node:_http_outgoing:977:5)
    at ServerResponse.send (E:\fundo-project\fundoo\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (E:\fundo-project\fundoo\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (E:\fundo-project\fundoo\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (E:\fundo-project\fundoo\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:326:13)
    at E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:468:21) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-11T05:17:59.235Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T05:22:47.949Z"}
info: Connected to the database. {"timestamp":"2022-11-11T05:22:48.013Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T05:23:04.153Z"}
info: Connected to the database. {"timestamp":"2022-11-11T05:23:04.219Z"}
error: 
    status - 500 
    message - ObjectParameterError: Parameter "filter" to findOne() must be an object, got sunilku007@gmail.com
    at model.Query.Query.findOne (E:\fundo-project\fundoo\node_modules\mongoose\lib\query.js:2321:16)
    at Function.findOne (E:\fundo-project\fundoo\node_modules\mongoose\lib\model.js:2267:13)
    at _callee5$ (E:\fundo-project\fundoo\src\services\/user.service.js:37:27)
    at tryCatch (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.getUser (E:\fundo-project\fundoo\src\services\/user.service.js:36:21)
    at _callee2$ (E:\fundo-project\fundoo\src\controllers\/user.controller.js:31:36)
    at tryCatch (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21) 
    url - /api/v1/users/sunilku007@gmail.com 
    method - GET 
    IP - ::1
   {"timestamp":"2022-11-11T05:23:29.512Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T05:24:44.039Z"}
info: Connected to the database. {"timestamp":"2022-11-11T05:24:44.102Z"}
error: 
    status - 500 
    message - ObjectParameterError: Parameter "filter" to findOne() must be an object, got sunilku007@gmail.com
    at model.Query.Query.findOne (E:\fundo-project\fundoo\node_modules\mongoose\lib\query.js:2321:16)
    at Function.findOne (E:\fundo-project\fundoo\node_modules\mongoose\lib\model.js:2267:13)
    at _callee5$ (E:\fundo-project\fundoo\src\services\/user.service.js:37:27)
    at tryCatch (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.getUser (E:\fundo-project\fundoo\src\services\/user.service.js:36:21)
    at _callee2$ (E:\fundo-project\fundoo\src\controllers\/user.controller.js:31:36)
    at tryCatch (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at getUser (E:\fundo-project\fundoo\src\controllers\/user.controller.js:29:21)
    at Layer.handle [as handle_request] (E:\fundo-project\fundoo\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\fundo-project\fundoo\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (E:\fundo-project\fundoo\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (E:\fundo-project\fundoo\node_modules\express\lib\router\layer.js:95:5)
    at E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:284:15
    at param (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:365:14)
    at param (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:421:3)
    at next (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:175:3)
    at router (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (E:\fundo-project\fundoo\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:328:13)
    at E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:346:12)
    at next (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:175:3)
    at router (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (E:\fundo-project\fundoo\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:328:13)
    at E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:346:12)
    at next (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:280:10)
    at logger (E:\fundo-project\fundoo\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (E:\fundo-project\fundoo\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:328:13)
    at E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:346:12)
    at next (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:280:10)
    at E:\fundo-project\fundoo\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (E:\fundo-project\fundoo\node_modules\raw-body\index.js:231:16)
    at done (E:\fundo-project\fundoo\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (E:\fundo-project\fundoo\node_modules\raw-body\index.js:280:7) 
    url - /api/v1/users/sunilku007@gmail.com 
    method - GET 
    IP - ::1
   {"timestamp":"2022-11-11T05:24:54.231Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T05:25:32.410Z"}
info: Connected to the database. {"timestamp":"2022-11-11T05:25:32.483Z"}
error: 
    status - 500 
    message - ObjectParameterError: Parameter "filter" to findOne() must be an object, got sunilah007@gmail.com
    at model.Query.Query.findOne (E:\fundo-project\fundoo\node_modules\mongoose\lib\query.js:2321:16)
    at Function.findOne (E:\fundo-project\fundoo\node_modules\mongoose\lib\model.js:2267:13)
    at _callee5$ (E:\fundo-project\fundoo\src\services\/user.service.js:37:27)
    at tryCatch (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.getUser (E:\fundo-project\fundoo\src\services\/user.service.js:36:21)
    at _callee2$ (E:\fundo-project\fundoo\src\controllers\/user.controller.js:31:36)
    at tryCatch (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21) 
    url - /api/v1/users/sunilah007@gmail.com 
    method - GET 
    IP - ::1
   {"timestamp":"2022-11-11T05:25:52.420Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T05:29:54.748Z"}
info: Connected to the database. {"timestamp":"2022-11-11T05:29:54.801Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T14:31:57.945Z"}
info: Connected to the database. {"timestamp":"2022-11-11T14:31:58.006Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T14:49:33.316Z"}
info: Connected to the database. {"timestamp":"2022-11-11T14:49:33.353Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T14:52:27.945Z"}
info: Connected to the database. {"timestamp":"2022-11-11T14:52:27.980Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T15:16:44.851Z"}
info: Connected to the database. {"timestamp":"2022-11-11T15:16:44.907Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T15:17:23.367Z"}
info: Connected to the database. {"timestamp":"2022-11-11T15:17:23.426Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T15:18:21.858Z"}
info: Connected to the database. {"timestamp":"2022-11-11T15:18:21.926Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T15:19:39.666Z"}
info: Connected to the database. {"timestamp":"2022-11-11T15:19:39.734Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T15:40:06.126Z"}
info: Connected to the database. {"timestamp":"2022-11-11T15:40:06.167Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T15:40:36.217Z"}
info: Connected to the database. {"timestamp":"2022-11-11T15:40:36.263Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T16:44:11.522Z"}
info: Connected to the database. {"timestamp":"2022-11-11T16:44:11.569Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T16:44:25.583Z"}
info: Connected to the database. {"timestamp":"2022-11-11T16:44:25.614Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T16:53:09.558Z"}
info: Connected to the database. {"timestamp":"2022-11-11T16:53:09.599Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T16:55:11.020Z"}
info: Connected to the database. {"timestamp":"2022-11-11T16:55:11.063Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T17:02:41.866Z"}
info: Connected to the database. {"timestamp":"2022-11-11T17:02:41.920Z"}
error: 
    status - 500 
    message - ValidationError: "lastname" length must be at least 4 characters long 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-11T17:05:13.180Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T17:07:55.984Z"}
info: Connected to the database. {"timestamp":"2022-11-11T17:07:56.039Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T17:16:40.316Z"}
info: Connected to the database. {"timestamp":"2022-11-11T17:16:40.354Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T17:16:56.862Z"}
info: Connected to the database. {"timestamp":"2022-11-11T17:16:56.937Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T17:41:10.407Z"}
info: Connected to the database. {"timestamp":"2022-11-11T17:41:10.484Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: fundoodb.users index: email_1 dup key: { email: "sunilku007@gmail.com" } 
      url - /api/v1/users/register 
      method - POST 
      IP - ::1
     {"timestamp":"2022-11-11T17:42:49.080Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.writeHead (node:_http_server:314:11)
    at ServerResponse.writeHead (E:\fundo-project\fundoo\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:305:8)
    at write_ (node:_http_outgoing:867:9)
    at ServerResponse.end (node:_http_outgoing:977:5)
    at ServerResponse.send (E:\fundo-project\fundoo\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (E:\fundo-project\fundoo\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (E:\fundo-project\fundoo\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (E:\fundo-project\fundoo\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:326:13)
    at E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (E:\fundo-project\fundoo\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:468:21) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-11T17:42:49.114Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T18:06:21.757Z"}
info: Connected to the database. {"timestamp":"2022-11-11T18:06:21.809Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T18:09:26.121Z"}
info: Connected to the database. {"timestamp":"2022-11-11T18:09:26.165Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T18:10:14.447Z"}
info: Connected to the database. {"timestamp":"2022-11-11T18:10:14.496Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T18:11:07.480Z"}
info: Connected to the database. {"timestamp":"2022-11-11T18:11:07.528Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T18:13:09.056Z"}
info: Connected to the database. {"timestamp":"2022-11-11T18:13:09.099Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T18:13:54.841Z"}
info: Connected to the database. {"timestamp":"2022-11-11T18:13:54.903Z"}
error: 
    status - 500 
    message - ReferenceError: res is not defined
    at _callee5$ (E:\fundo-project\fundoo\src\services\/user.service.js:40:12)
    at tryCatch (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-11T18:14:01.760Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T18:15:13.243Z"}
info: Connected to the database. {"timestamp":"2022-11-11T18:15:13.291Z"}
error: 
    status - 500 
    message - ReferenceError: res is not defined
    at _callee5$ (E:\fundo-project\fundoo\src\services\/user.service.js:40:12)
    at tryCatch (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-11T18:15:20.684Z"}
error: 
    status - 500 
    message - ReferenceError: res is not defined
    at _callee5$ (E:\fundo-project\fundoo\src\services\/user.service.js:40:12)
    at tryCatch (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-11T18:15:58.753Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T18:16:18.327Z"}
info: Connected to the database. {"timestamp":"2022-11-11T18:16:18.394Z"}
error: 
    status - 500 
    message - ReferenceError: res is not defined
    at _callee5$ (E:\fundo-project\fundoo\src\services\/user.service.js:40:12)
    at tryCatch (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-11T18:16:24.593Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T18:25:09.611Z"}
info: Connected to the database. {"timestamp":"2022-11-11T18:25:09.662Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'status')
    at _callee5$ (E:\fundo-project\fundoo\src\services\/user.service.js:40:16)
    at tryCatch (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-11T18:25:14.132Z"}
